# Generated by Django 4.1.5 on 2023-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
